# Uncomment this line to define a global platform for your project
platform :ios, '13.4'

# Uncomment this line if you're using Swift
use_frameworks!
inhibit_all_warnings!

target 'Jekheha' do

  # pod 'googleapis', :path => '.'
  # pod 'AuthLibrary', :git => 'https://github.com/google/auth-library-swift.git'
  # pod 'MaterialComponents'
  pod 'Firebase/Messaging'


end


